Limit what upload script accepts as version
Signed-off-by: Michal Čihař <michal@cihar.com>

diff --git a/scripts/upload-release b/scripts/upload-release
--- a/scripts/upload-release
+++ b/scripts/upload-release
@@ -8,7 +8,11 @@ if [ $# -lt 2 ] ; then
     echo 'Must be called in directory with binaries or with path'
     exit 1
 fi
-REL=$1
+REL=`echo $1 | tr -d -c '0-9a-z.-'`
+if [ "x$REL" != "x$1" ] ; then
+    echo "Invalid version: $1"
+    exit 1
+fi
 
 if [ $# -gt 1 ] ; then
     cd "$2"
